# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-13 14:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CiscoDevice',
            fields=[
                ('device_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('ios_version', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='IosVulnerability',
            fields=[
                ('cisco_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('url', models.URLField(max_length=300)),
                ('description', models.TextField()),
                ('severity', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='VulnMapper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ios_version', models.CharField(max_length=100)),
                ('affecting', models.BooleanField()),
                ('device_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IosVulnCheckApp.CiscoDevice')),
                ('vulnerab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IosVulnCheckApp.IosVulnerability')),
            ],
        ),
        migrations.AddField(
            model_name='ciscodevice',
            name='vulnerabs',
            field=models.ManyToManyField(through='IosVulnCheckApp.VulnMapper', to='IosVulnCheckApp.IosVulnerability'),
        ),
    ]
