# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-25 08:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IosVulnCheckApp', '0002_ciscodevice_ios_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vulnmapper',
            old_name='device_name',
            new_name='device',
        ),
    ]
