# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-25 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IosVulnCheckApp', '0003_auto_20180525_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vulnmapper',
            name='affecting',
            field=models.BooleanField(default=False),
        ),
    ]
